### ISSUE TITLE
Zoom in and out 

### ISSUE THREAD

**Issue by arthurlogilab** [movim/movim_electron#10]
Some electron applications that I use have a general zoom in / zoom out functionality which is useful (if not essential) to get the working on an HDPI setup. It would be really cool (and useful) for movim-desktop to be able to do that too.

**Comment by arthurlogilab** [comment]
Maybe this is a matter of recompiling movim with a recent version of electron that uses a recent version of libchromium that supports this ? see https://github.com/electron/electron/issues/8062 (no I'm not using windows ;-) )

**Comment by arthurlogilab** [comment]
Après avoir recompilé, il plante sur : 

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-window-state'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/movim/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/movim/resources/app/main.js:2:27)
    at Object.<anonymous> (/opt/movim/resources/app/main.js:115:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by dos1** [comment]
#24 provides an ability to manually zoom in/out using keyboard shortcuts. Also, new Electron builds should handle hidpi just fine. BTW. new premade builds should be published soon.

Your error message means you probably missed "npm install" on package's contents.
