### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by Kidlike** [movim/movim_electron#11]
I'm running Fedora 27, installed electron from npm.
```
$ electron -v
v1.7.9

$ npm -v
5.5.1

$ node -v
v8.9.1
```
When I try to run movim (using the command in your readme), I get this:
```
$ electron movim_electron/movim/.
App threw an error during load
Error: Cannot find module 'electron-window-state'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/lib/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kidlike/install/source/movim_electron/movim/main.js:2:27)
    at Object.<anonymous> (/home/kidlike/install/source/movim_electron/movim/main.js:115:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-window-state'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/lib/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kidlike/install/source/movim_electron/movim/main.js:2:27)
    at Object.<anonymous> (/home/kidlike/install/source/movim_electron/movim/main.js:115:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

```

**Comment by Kidlike** [comment]
Nevermind... I figured it out...

```
cd movim_electron/movim
npm install
```
