### ISSUE TITLE
Error: Cannot find module 'electron-window-state'

### ISSUE THREAD

**Issue by stevenroose** [movim/movim_electron#15]
Like the README says, I cloned the repo and installed electron (Arch). When running `electron movin/` I get this error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-window-state'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/steven/code/movim_electron/movim/main.js:2:27)
    at Object.<anonymous> (/home/steven/code/movim_electron/movim/main.js:115:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by maddanio** [comment]
same here on osx

**Comment by maddanio** [comment]
ok, so i had to install two more modules. in total 3:
npm install electron --save-dev --save-exact
npm install --save electron-window-state
npm install --save electron-context-menu
./node_modules/.bin/electron movim/

**Comment by maddanio** [comment]
but now nothing happens, i can click pods in a list, but nothing happens afterwards...

**Comment by dos1** [comment]
FYI: you need to do `npm install` on both the root directory, and the `movim` subdirectory.

Also, you need to click `Next` button after clicking/typing in a pod :P
